import type { Metadata } from "next";
import "./globals.css";
import { Box, Container, Stack, Typography } from "@mui/material";
import NarBar from "@/components/nav-bar";
import RootProviders from "@/components/root-providers";


export const metadata: Metadata = {
	title: "On Track",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
		>
			<body>
				<Stack sx={{ height: "100vh" }} >

					<Container sx={{ background: "#b2c0d6", p:"1%" }}>
						<Typography variant="h5">🫐 On Track</Typography>
					</Container>
					<Container sx={{ flex: 1, mt: "10pt" }} >
						<RootProviders>
							{children}
						</RootProviders>
					</Container>
					<Box >
						<NarBar />
					</Box>
				</Stack>
			</body>
		</html >
	);
}
