import type { Metadata } from "next";
import "./globals.css";
import { Box, Container, Stack } from "@mui/material";
import NarBar from "@/components/nav-bar";
import RootProviders from "@/components/root-providers";


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
		>
			<body>
				<Stack sx={{ height: "100vh" }} >

					<Container sx={{ flex: 1 }}>
						<RootProviders>
							{children}
						</RootProviders>
					</Container>
					<Box >
						<NarBar />
					</Box>
				</Stack>
			</body>
		</html >
	);
}
